version: '3.9'

services:
  pg12:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: tests/docker
      dockerfile: postgres12-wal2json/Dockerfile
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54012:5432
    command:
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      #  - -c
      #  - fsync=off
      #  - -c
      #  - full_page_writes=off
    stop_grace_period: 2s

  pg13:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: tests/docker
      dockerfile: postgres13-wal2json/Dockerfile
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54013:5432
    command:
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      #  - -c
      #  - fsync=off
      #  - -c
      #  - full_page_writes=off
    stop_grace_period: 2s

  pg14:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: tests/docker
      dockerfile: postgres14-wal2json/Dockerfile
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54014:5432
    command:
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      #  - -c
      #  - fsync=off
      #  - -c
      #  - full_page_writes=off
    stop_grace_period: 2s

  pg15:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: tests/docker
      dockerfile: postgres15-wal2json/Dockerfile
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54015:5432
    command:
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      #  - -c
      #  - fsync=off
      #  - -c
      #  - full_page_writes=off
    stop_grace_period: 2s

  pg16:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: tests/docker
      dockerfile: postgres16-wal2json/Dockerfile
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54016:5432
    command:
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      #  - -c
      #  - fsync=off
      #  - -c
      #  - full_page_writes=off

    stop_grace_period: 2s

  db-activity-simulator:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: tests/docker/db-activity-simulator
    restart: no
    shm_size: 128mb
    environment:
      DSN_ACTIVITY_SIMULATOR: "postgresql://postgres:pass@pg16:5432/popyka_test"
    stop_grace_period: 1s
    stop_signal: SIGKILL
    # We don't want `pg16` to be stopped
    #    depends_on:
    #      - pg16

  popyka:
    build:
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
      context: .
    restart: no
    shm_size: 128mb
    depends_on:
      - db-activity-simulator
    environment:
      POPYKA_CONFIG: "${POPYKA_CONFIG:-}"
      POPYKA_DB_DSN: "postgresql://postgres:pass@pg16:5432/popyka_test"
      POPYKA_PYTHONPATH: "${POPYKA_PYTHONPATH:-}"
      POPYKA_DB_SLOT_NAME: "${POPYKA_DB_SLOT_NAME:-}"
      LAZYTOSTR_COMPACT: "${LAZYTOSTR_COMPACT:-}"
      POPYKA_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      POPYKA_KAFKA_TOPIC: "${POPYKA_KAFKA_TOPIC:-}"
    stop_grace_period: 1s
    stop_signal: SIGKILL
    volumes:
      - ./tests/resources/external-repository:/external-repository

  kafka:
    image: 'bitnami/kafka:3.5'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - 9092:9092
      - 9094:9094

  kowl:
    image: docker.redpanda.com/redpandadata/console:latest
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - 8080:8080
