# Generated by Django 5.0.4 on 2024-04-11 13:18
from django.contrib.auth.models import User
from django.db import migrations


def create_superuser(app_label, state):
    User.objects.create_superuser("admin", email="admin@example.com", password="admin")


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_superuser),
    ]
